// Frontend-only domain types for the connector UI. These mirror the intended
// backend model (api_details, transformers, unified_endpoints) and will be
// swapped for real API calls once the backend endpoints exist.

export type SecurityScheme =
  | "NONE"
  | "API_KEY"
  | "BEARER_TOKEN"
  | "BASIC"
  | "OAUTH2"
  | "HMAC";

export type DataFormat = "JSON" | "XML" | "CSV" | "SOAP" | "FORM_URLENCODED";

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

/** How the uniform endpoint returns data to the client. */
export type ResponseMode = "DIRECT" | "WEBHOOK" | "AI_INSIGHT";

export type ConnectionStatus = "ACTIVE" | "DRAFT" | "ERROR";

export interface ThirdPartyApi {
  id: string;
  name: string;
  baseUrl: string;
  method: HttpMethod;
  format: DataFormat;
  security: SecurityScheme;
  responseMode: ResponseMode;
  status: ConnectionStatus;
  /** Uniform, client-facing path generated by APIConnector. */
  uniformPath: string;
  /** Platform AI provider ("ANTHROPIC"/"OPENAI") used to analyze AI_INSIGHT responses. Pro plan only. */
  aiProvider: string | null;
  createdAt: string;
}

/** A "set" = an isolated workspace grouping a batch of third-party APIs. */
export interface ApiSet {
  id: string;
  name: string;
  description?: string;
  apis: ThirdPartyApi[];
}

/** Free-token allotment that decrements as the user exercises the platform. */
export interface UsageTokens {
  total: number;
  used: number;
}

export const SECURITY_LABELS: Record<SecurityScheme, string> = {
  NONE: "None",
  API_KEY: "API Key",
  BEARER_TOKEN: "Bearer Token",
  BASIC: "Basic Auth",
  OAUTH2: "OAuth 2.0",
  HMAC: "HMAC Signature",
};

export const RESPONSE_MODE_LABELS: Record<ResponseMode, string> = {
  DIRECT: "Direct (sync JSON)",
  WEBHOOK: "Webhook callback",
  AI_INSIGHT: "AI-processed response",
};
